{"content": ["\r\nAt least one of the people named in the Brussels attack had been deported by Turkey with indications that he was a jihadist."], "link": ["http://www.nytimes.com/2016/03/24/world/europe/as-terrorists-cross-borders-europe-sees-anew-that-its-intelligence-does-not.html?ref=world"], "title": ["\nAs Terrorists Cross Borders, Europe Sees Anew That Its Intelligence Does Not"]}
{"content": ["\r\nIbrahim el-Bakraoui attacked the airport and his brother Khalid attacked the subway, Belgian officials said, as an inquiry drew links to the 2015 Paris attacks."], "link": ["http://www.nytimes.com/2016/03/24/world/europe/brussels-attack.html?ref=world"], "title": ["\nBrothers Among 3 Brussels Suicide Attackers; Another Assailant Is Sought"]}
{"content": ["\r\nFor European leaders, who see themselves as at war with the Islamic State, the problem is that the enemy\u2019s hide-outs are not in a faraway failed state."], "link": ["http://www.nytimes.com/2016/03/24/world/europe/a-quandary-for-europe-fighting-a-war-on-isis-within-its-borders.html?ref=world"], "title": ["\nA Quandary for Europe: Fighting a War on ISIS Within Its Borders"]}
{"content": ["\r\nMr. Abdeslam, captured in Belgium, reversed his position after the bombings in Brussels, which killed at least 31 and wounded about 300 on Tuesday."], "link": ["http://www.nytimes.com/2016/03/25/world/europe/brussels-attacks.html?ref=world"], "title": ["\nSalah Abdeslam, Suspect in Paris Attacks, Seeks Extradition to France"]}
{"content": ["\r\nGovernment troops and allied militias, backed by intensive Russian airstrikes, are fighting to retake the city, along with its majestic ancient ruins."], "link": ["http://www.nytimes.com/2016/03/25/world/middleeast/syria-palmyra-isis.html?ref=world"], "title": ["\nSyrian Forces and ISIS Clash at Edge of Palmyra"]}
{"content": ["\r\nMajd Oweida, 22, was arrested on his way out of Gaza. He said he was seeking contestants for a show, but he was charged with hacking airport computers."], "link": ["http://www.nytimes.com/2016/03/24/world/middleeast/family-sees-tv-talent-scout-where-israeli-authorities-see-jihadist-spy.html?ref=world"], "title": ["\nFamily Sees TV Talent Scout Where Israeli Authorities See Jihadist Spy"]}
{"content": ["\r\nThe test of the design, a solid-fuel rocket engine, would decrease the time needed to prepare the launch of a missile, defense officials said."], "link": ["http://www.nytimes.com/2016/03/25/world/asia/north-korea-solid-fuel-rocket-engine.html?ref=world"], "title": ["\nNorth Korea Tests New Rocket Engine, State Media Says"]}
{"content": ["\r\nThe explosive, triacetone triperoxide, can be made with basic chemistry skills and relatively simple equipment, but the process is risky and tedious."], "link": ["http://www.nytimes.com/2016/03/24/world/europe/brussels-explosives-tatp.html?ref=world"], "title": ["\nQuantity of Explosive Found in Belgium Surprises Officials"]}
{"content": ["\r\nThe pregnant Japanese-Australian woman was arrested while on vacation in Singapore with her husband, who also faces charges."], "link": ["http://www.nytimes.com/2016/03/24/world/asia/blogger-gets-jail-term-in-singapore-for-posts-said-to-incite-ethnic-hatred.html?ref=world"], "title": ["\nBlogger Gets Jail Term in Singapore for Posts Said to Incite Ethnic Hatred"]}
{"content": ["\r\nIntelligence and police agencies must cooperate, rail and air travel must be made secure, and authorities need to earn the trust of Muslims."], "link": ["http://www.nytimes.com/2016/03/24/opinion/steps-that-europe-must-take-now-after-brussels.html?ref=world"], "title": ["\nSteps That Europe Must Take Now After Brussels"]}
{"content": ["\r\nChina has been feverishly piling sand onto reefs in the South China Sea, creating seven new islets in the region and straining already taut geopolitical tensions."], "link": [], "title": []}
{"content": ["\r\nThe justice and interior ministers said officials might have been lax in passing along information about a terrorism suspect and offered to resign."], "link": ["http://www.nytimes.com/2016/03/25/world/europe/brussels-attacks.html?ref=world"], "title": ["\nBrussels Attack Lapses Acknowledged by Belgian Officials"]}
{"content": ["\r\nThe terrorism suspect\u2019s capture has raised the prospect of an intelligence bonanza, but there are reasons to doubt that he will be of much help."], "link": ["http://www.nytimes.com/2016/03/25/world/europe/experts-question-whether-salah-abdeslam-will-provide-answers-on-attacks.html?ref=world"], "title": ["\nExperts Question Whether Salah Abdeslam Will Provide Answers on Attacks"]}
{"content": ["\r\nThe French interior minister said the authorities were raiding an apartment building in the northern suburbs of Paris after the arrest."], "link": ["http://www.nytimes.com/2016/03/25/world/europe/france-arrests-citizen-tied-to-terrorist-plot-in-advanced-stages.html?ref=world"], "title": ["\nFrance Arrests Citizen Tied to Terrorist Plot in \u2018Advanced Stages\u2019"]}
{"content": ["\r\nKhalid el-Bakraoui, one of the suicide bombers in Brussels, was listed as a Bahamian citizen in an Interpol arrest warrant because of a \u201cclerical error.\u201d"], "link": ["http://www.nytimes.com/2016/03/25/world/europe/brussels-suicide-bomber-wasnt-one-of-ours-bahamas-says.html?ref=world"], "title": ["\nBrussels Suicide Bomber Wasn\u2019t One of Ours, Bahamas Says"]}
{"content": ["\r\nThe Australian authorities said that two pieces of debris found in Mozambique were very likely to have come from the missing jetliner."], "link": ["http://www.nytimes.com/2016/03/24/world/australia/mh370-debris.html?ref=world"], "title": ["\nDebris Is Probably From Malaysia Airlines Flight 370, Investigators Say"]}
{"content": ["\r\nDeng Jingquan, also known as Frank Deng, had founded in Internet start-up not long after finishing college."], "link": ["http://www.nytimes.com/2016/03/27/world/europe/frank-deng-spirited-chinese-entrepreneur-and-brussels-victim.html?ref=world"], "title": ["\nFrank Deng, \u2018Spirited\u2019 Chinese Entrepreneur and Brussels Victim"]}
{"content": ["\r\nChoe Sang-Hun, The Times\u2019s Seoul bureau chief, describes his coverage of a Go match between Lee So-dol and Google\u2019s AlphaGo."], "link": [], "title": []}
{"content": ["\r\nMobile phones smuggled from China are an increasingly vital way for North Koreans to reach relatives who have defected abroad."], "link": ["http://www.nytimes.com/2016/03/27/world/asia/north-korea-china-mobile-phones.html?ref=world"], "title": ["\nNorth Koreans Rely on Smuggled Cellphones to Connect to the Outside World"]}
{"content": ["\r\nThe United States has a longer history of military intervention in what is now Libya than in any other country, dating from the Jefferson administration and America\u2019s first foreign war."], "link": [], "title": []}
{"content": ["\r\nCritics of the German leader\u2019s new deal say it may violate human rights standards, particularly as Turkey veers from democracy and Greece struggles to process refugees."], "link": ["http://www.nytimes.com/2016/03/21/world/europe/angela-merkel-faces-criticism-over-agreement-with-turkey.html?ref=world"], "title": ["\nAngela Merkel\u2019s Trust in Turkey and Greece on Migrants Comes With Risks"]}
{"content": ["\r\nThe founder of the social networking service has learned Mandarin and charmed audiences. But with a public presence in China comes official scrutiny."], "link": ["http://www.nytimes.com/2016/03/21/business/seeking-access-to-facebook-in-china-zuckerberg-courts-risks.html?ref=world"], "title": ["\nSeeking Access to Facebook in China, Zuckerberg Courts Risks"]}
{"content": ["\r\nMr. Zhang discusses his early embrace of Mao\u2019s teachings, his family\u2019s tribulations and what he hoped his art would accomplish."], "link": ["http://www.nytimes.com/2016/03/22/world/asia/zhang-hongtu-artist-mao-china.html?ref=world"], "title": ["\nQ. and A.: The Artist Zhang Hongtu on Appropriating Mao\u2019s Image"]}